[tasks]
[tasks.binarytree]
algorithm = "binary_tree"
debug = false
data = [0, 1, 69, 2, 3]
script = """
local aboba = tree:in_order()
print("Симметричный обход:")
print_array(aboba)

aboba = tree:pre_order()
print("Прямой обход:")
print_array(aboba)

aboba = tree:post_order()
print("Обратный обход:")
print_array(aboba)
"""

