[tasks]
[tasks.rbtree]
algorithm = "rb_tree"
debug = true
data = [25, 20, 10, 19, 44, 15, 54, 61, 39, 7, 22]
script = """
function try_find_node(n)
	local number = tree:find(n)
	if number == nil then
		print("Число " .. tostring(n) .. " не найдено")
	else
		print("Число " .. tostring(n) .. " найдено")
	end
end

try_find_node(69)
try_find_node(42)

tree:print()
tree:insert(42)
tree:print()
tree:remove(54)
tree:print()

try_find_node(69)
try_find_node(42)

"""